server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: vakporize
    url: jdbc:mysql://localhost:3306/java_cardeal
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      basePath: /api

ng:
  com:
    createsoftware:
      secretkey: VAXXINE_SECRETKEY